<?php

/**
 * @file
 * Contains capture+ implementation for webform.
 */


define('WEBFORM_CAPTUREPLUS_FIELD_MODE_DEFAULT', 3);
define('WEBFORM_CAPTUREPLUS_FIELD_MODE_NONE', 0);
define('WEBFORM_CAPTUREPLUS_FIELD_MODE_SEARCH', 1);
define('WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE', 2);
define('WEBFORM_CAPTUREPLUS_FIELD_MODE_PRESERVE', 4);
define('WEBFORM_CAPTUREPLUS_FIELD_MODE_COUNTRY', 8);

/**
 * Implements hook_menu().
 */
function webform_captureplus_menu() {
  $items['node/%webform_menu/webform/captureplus'] = array(
    'title' => 'Capture+ settings',
    'page callback' => 'webform_captureplus_page',
    'page arguments' => array( 1),
    'access callback' => 'webform_node_update_access',
    'access arguments' => array(1),
    'file' => 'includes/admin.inc',
    'weight' => 6,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function webform_captureplus_theme($existing, $type, $theme, $path) {
  return array(
    'webform_captureplus_page' => array(
      'variables' => array('node' => NULL, 'form' => NULL),
      'file' => 'includes/theme.inc',
    ),
    'webform_captureplus_form' => array(
      'render element' => 'form',
      'file' => 'includes/theme.inc',
    ),
  );
}
/**
 * Implements hook_permission().
 */
function webform_captureplus_permission() {
  return array(
    'administer webform capture plus' => array(
      'title' => t('Administer webform capture plus'),
    ),
  );
}
/**
 * Implements hook_form_alter().
 *
 * Add capture+ settings
 */
function webform_captureplus_form_alter(&$form, $form_state, $form_id) {
  static $called_forms = array();

  if (strstr($form_id, 'webform_client_form_') && isset($form['submitted'])) {
    if (isset($form['#webform_captureplus_js'])) {
      return;
    }
    $nid = $form['details']['nid']['#value'];
    if (in_array($nid, $called_forms)) {
      //return;
    }
    else {
      $called_forms[] = $nid;
    }

    // Get the components.
    $sql = "SELECT * FROM {webform_component} where nid = :nid";
    $result = db_query($sql, array(':nid' => $nid));
    while ($row = $result->fetchAssoc()) {
      $rows[$row['cid']] = $row;
    }
    foreach ($rows as $row) {
      // Generate from webform.
    }

    //can't add javascript in this function or it will not be added if the form is built from cache.  Need to run "after_build" function
    $form['#after_build'][] = 'webform_captureplus_add_js';
    // @todo: replace with settings form values.
    $fields = array(
      array('element' => 'submitted[company]', 'field' => 'Company', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE),
      array('element' => 'submitted[department]', 'field' => 'Department', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE),
      array('element' => 'submitted[address_line_1]', 'field' => 'Line1', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE),
      array('element' => 'submitted[address_line_2]', 'field' => 'Line2', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE),
      array('element' => 'submitted[city]', 'field' => 'City', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_POPULATE),
      array('element' => 'submitted[postcode]', 'field' => 'PostalCode', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_DEFAULT),
      array('element' => 'submitted[country]', 'field' => 'Country', 'mode' => WEBFORM_CAPTUREPLUS_FIELD_MODE_COUNTRY),
    );

    $js_settings = array(
      'setCursor' => TRUE,
      'countries' => (object) array('codesList' => 'GBR'),
      'list' => (object) array('width' => 590, 'height' => 200),
      'bar' => (object) array('visible' => FALSE),
      'culture' => 'EN-GB',
      'fields' => $fields,
      'key' => variable_get('capture_plus_key', '')
    );
    //store JavaScript variable for the webform_captureplus_add_js function
    $form['#webform_captureplus_js'] = array('webform_captureplus_' . $form_id => $js_settings);
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function webform_captureplus_form_webform_admin_settings_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'webform_captureplus', 'includes/admin');
  $capture_plus_version = variable_get('webform_captureplus_version', '3.20');
  $form['captureplus'] = array(
    '#type' => 'fieldset',
    '#title' => t('Capture+ settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 19,
  );

  $form['captureplus']['webform_captureplus_domain'] = array(
    '#title' => t('Capture+ domain'),
    '#type' => 'textfield',
    '#default_value' => variable_get('webform_captureplus_domain', 'services.postcodeanywhere.co.uk'),
    '#description' => t('Capture+ domain to make service calls.'),
  );
  $form['captureplus']['webform_captureplus_version'] = array(
    '#title' => t('Capture+ API version'),
    '#type' => 'textfield',
    '#default_value' => $capture_plus_version,
    '#description' => t('Capture+ API version'),
  );
  $form['captureplus']['webform_captureplus_allowed_fields'] = array(
    '#title' => t('Allowed fields'),
    '#type' => 'checkboxes',
    '#options' => webform_captureplus_get_field_mappings(),
    '#default_value' => variable_get('webform_captureplus_allowed_fields', array()),
    '#description' => t('Allowed fields to map in webform. Check <a href="!link">Capture+ documentation</a> for more details.', array('!link' => 'http://www.pcapredict.com/support/webservice/captureplus/interactive/retrieve/' . $capture_plus_version . '/')),
  );
}
/**
 * Function run #after_build on webform.  This ensures that Javascript is added even if form is built from cache.
 * @param array $form
 * @param array $form_state
 * @return array
 *  The form
 */
function webform_captureplus_add_js(&$form, $form_state) {
  // If the form is being rebuilt we need to reset the previous settings,
  // otherwise array_merge_recursive() will turn string values into arrays.
  $javascript = &drupal_static('drupal_add_js', array());
  foreach ($javascript['settings']['data'] as $delta => $settings) {
    if (key($settings) == 'webform_captureplus') {
      unset($javascript['settings']['data'][$delta]);
      break;
    }
  }
  drupal_add_js($form['#webform_captureplus_js'], array('type' => "setting", 'scope' => JS_DEFAULT));
  drupal_add_js(drupal_get_path('module', 'webform_captureplus') . '/js/webform_captureplus.js');

  webform_captureplus_add_lib();
  return $form;
}

/**
 * Add css/js libraries.
 */
function webform_captureplus_add_lib() {
  // Including Capture+ js and css.
  $capture_plus_domain = variable_get('webform_captureplus_domain', 'services.postcodeanywhere.co.uk');
  $capture_plus_version = variable_get('webform_captureplus_version', '3.20');
  drupal_add_js("//$capture_plus_domain/js/address-$capture_plus_version.min.js", array('type' => 'external'));
  drupal_add_css("//$capture_plus_domain/css/address-$capture_plus_version.min.css", array('type' => 'external'));

  // Allow modules to override.
  module_invoke_all('webform_captureplus_add_lib');
}
